on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rego.yml@7bc76e326b9c29582dd89eaf1b9efad1da3d3872 # v4.6.3
    with:
      opa-version: v1.5.1
